name: crisprme
channels:
  - conda-forge
  - anaconda
  - bioconda
  - defaults
dependencies:
  - zip
  - crispritz
  - dash=1.10.0
  - dash-bootstrap-components=0.10.0
  - dash-core-components=1.9.0
  - dash-daq=0.4.0
  - dash-html-components=1.0.3
  - dash-renderer=1.3.0
  - dash-table=4.6.2
  - flask=1.1.2
  - flask-caching=1.7.1
  - flask-compress=1.5.0
  - fontconfig=2.13.1
  - freetype=2.10.1
  - future=0.18.2
  - gettext=0.19.8.1
  - gunicorn=20.0.4
  # - pip
  # - pip:
  #   - astroid==2.4.0
  #   - isort==4.3.21
  #   - lazy-object-proxy==1.4.3
  #   - mccabe==0.6.1
  #   - pylint==2.5.0
  #   - toml==0.10.0
  #   - wrapt==1.12.1
